global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'monitoring'
    environment: 'production'

# rule_files:
#   - 'alerts/*.yml'

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: 'telegraf'
    file_sd_configs:
      - files:
          - '/etc/prometheus/targets-telegraf.json'
        refresh_interval: 30s

  - job_name: 'node-exporter'
    file_sd_configs:
      - files:
          - '/etc/prometheus/targets-node-exporter.json'
        refresh_interval: 30s

