apiVersion: 1

datasources:
  # Prometheus datasource commented out to avoid duplicate rules
  # Use Thanos Query instead which aggregates Prometheus + S3
  # - name: Prometheus
  #   type: prometheus
  #   uid: prometheus
  #   access: proxy
  #   url: http://nginx-proxy/prometheus
  #   isDefault: false
  #   editable: true

  - name: Thanos Query
    type: prometheus
    uid: thanos-query
    access: proxy
    url: http://nginx-proxy/thanos
    isDefault: true
    editable: true

  - name: Loki
    type: loki
    uid: loki
    access: proxy
    url: http://nginx-proxy/loki
    editable: true

