type: S3
config:
  bucket: adeaobserv
  endpoint: s3.ap-south-1.amazonaws.com
  region: ap-south-1
  access_key: AKIAVLDYJGKOCGW3BNXP
  secret_key: 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
  # prefix field not supported in Thanos v0.32.5
  # To organize data in folders, consider using a dedicated S3 bucket or upgrading Thanos
  insecure: false
  signature_version2: false
  put_user_metadata: {}
  http_config:
    idle_conn_timeout: 90s
    response_header_timeout: 0s
    insecure_skip_verify: false
  trace:
    enable: false

